# Generated by Django 4.2.16 on 2024-11-26 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_language', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(max_length=500, null=True)),
                ('backdrop_path', models.CharField(max_length=500, null=True)),
                ('genre_ids', models.JSONField()),
                ('adult', models.BooleanField()),
                ('popularity', models.DecimalField(decimal_places=3, default=None, max_digits=20)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=20)),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
